package com.medicapp.ui.theme

import androidx.compose.ui.graphics.Color

// Palette claire
val MedicTealLight = Color(0xFF006A60)
val OnMedicTealLight = Color(0xFFFFFFFF)
val MedicTealContainerLight = Color(0xFF9CF1E4)
val OnMedicTealContainerLight = Color(0xFF00201C)
val SecondaryLight = Color(0xFF4A635D)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8E0)
val OnSecondaryContainerLight = Color(0xFF06201B)
val TertiaryLight = Color(0xFF456179)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFCCE5FF)
val OnTertiaryContainerLight = Color(0xFF001E31)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF5FBF8)
val OnBackgroundLight = Color(0xFF171D1B)
val SurfaceLight = Color(0xFFF5FBF8)
val OnSurfaceLight = Color(0xFF171D1B)
val SurfaceVariantLight = Color(0xFFDBE5E1)
val OnSurfaceVariantLight = Color(0xFF3F4946)
val OutlineLight = Color(0xFF6F7976)

// Palette sombre
val MedicTealDark = Color(0xFF80D5C8)
val OnMedicTealDark = Color(0xFF003731)
val MedicTealContainerDark = Color(0xFF005048)
val OnMedicTealContainerDark = Color(0xFF9CF1E4)
val SecondaryDark = Color(0xFFB0CCC4)
val OnSecondaryDark = Color(0xFF1C3530)
val SecondaryContainerDark = Color(0xFF334B46)
val OnSecondaryContainerDark = Color(0xFFCCE8E0)
val TertiaryDark = Color(0xFFADCAE5)
val OnTertiaryDark = Color(0xFF143349)
val TertiaryContainerDark = Color(0xFF2D4961)
val OnTertiaryContainerDark = Color(0xFFCCE5FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF0F1513)
val OnBackgroundDark = Color(0xFFDEE4E1)
val SurfaceDark = Color(0xFF0F1513)
val OnSurfaceDark = Color(0xFFDEE4E1)
val SurfaceVariantDark = Color(0xFF3F4946)
val OnSurfaceVariantDark = Color(0xFFBFC9C5)
val OutlineDark = Color(0xFF899390)
